### PR TITLE
fix(utilities/math): export circle math utilities

### PR DESCRIPTION
**Pull request by JSweet314**
### Context

This change adds the circle math utilities to the export of the math utilities directory so that they are available to library users building custom tools involving circles.

### Changes & Results

Add export of circle math utilities to tools/utilities/math/index.ts.

### Testing

Import the circle math utilities into a custom tool that needs them.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by sedghi** [comment]
can you update the api and push back the generated files? https://www.cornerstonejs.org/docs/contribute/update-api

**Comment by JSweet314** [comment]
> can you update the api and push back the generated files? https://www.cornerstonejs.org/docs/contribute/update-api

There seems to be some errors in the `ONNXSegementationController.ts` file preventing the update of the api and generated files. 

```
src/ONNXSegmentationController.ts:8:3 - error TS2305: Module '"@cornerstonejs/tools"' has no exported member 'LabelmapBaseTool'.

8   LabelmapBaseTool,
    ~~~~~~~~~~~~~~~~

src/ONNXSegmentationController.ts:11:9 - error TS2339: Property 'strategies' does not exist on type 'typeof import("/Users/jsweet/projects/cornerstone3D/packages/tools/dist/esm/stateManagement/segmentation/index")'.

11 const { strategies } = cstSegmentation;
           ~~~~~~~~~~

src/ONNXSegmentationController.ts:25:9 - error TS2339: Property 'IslandRemoval' does not exist on type 'typeof import("/Users/jsweet/projects/cornerstone3D/packages/tools/dist/esm/utilities/index")'.

25 const { IslandRemoval } = cornerstoneTools.utilities;
           ~~~~~~~~~~~~~

src/ONNXSegmentationController.ts:433:18 - error TS2339: Property 'interpolationUID' does not exist on type 'Annotation'.

433       annotation.interpolationUID ||= crypto.randomUUID();
                     ~~~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: src/ONNXSegmentationController.ts:8
```

Do you want me to try and fix these or do you have any guidance if there is something I may be missing to update the API and generated files?

**Comment by sedghi** [comment]
I had to run `yarn run build` first just FYI

**Review by sedghi — APPROVED** [review]
Thanks

**Pull request merged**
