### PR TITLE
Feature/threshold optional center and threshold area

### PR DESCRIPTION
**Pull request by pavel-kaiko**
### Context

- **Issue Link**: N/A
- **Problem Description**: We want to show the threshold for the whole slice.
- **Error Logs**: N/A

- **Specific Requirements**: The threshold needs to be displayed for the entire viewport (slice).
- **Design/UI Guidelines**: No specific guidelines.
- **Integration with Existing Functionality**: Extra flags have been added to ensure backwards compatibility and make the functionality more flexible.
- **Performance Considerations**: No performance issues for one viewport. Volume visualization is currently out of scope.
- **Specific Test Cases/Scenarios**: There are issues with MPR mode (checked during OHIF Viewer integration), where it doesn't recognize any existing segments. Also I need some help with proper edge coordinates for AreaFill (some of them are currently hardcoded with approximate values).

### Changes & Results

- **Changes Made**:
  - Added area-fill strategy composition and manual preview mode.
  - Refactored `fillCircle` by extracting helper functions to improve code readability.
  - No old components were removed.
  - No dependencies were updated.

- **Effects of Changes**:
  - **Before**: Threshold was not displayed for the entire slice.
  - **After**: Threshold is now displayed for the entire slice.

- **Screenshots**:
  - **Before**: N/A (Videos are attached below)
  - **After**: N/A (Videos are attached below)

### Testing

- **Steps to Test**:
  - Run the command `npm run example -- labelmapSegmentationDynamicThreshold`.
  - Open a browser and navigate to `http://localhost:3000`.
  - Ensure the slice is displayed with the threshold correctly shown.

- **Test Cases**:
  - Threshold area with CenterJDK disabled by default
  
[Threshold area with CenterJDK disabled by default.](https://github.com/cornerstonejs/cornerstone3D/assets/143810329/fd5bcb1e-de61-4993-a117-65737da601f5)

 - Threshold circle with enabled and disabled CenterJDK 
 
 [Threshold circle with enabled and disabled CenterJDK.](https://github.com/cornerstonejs/cornerstone3D/assets/143810329/c47c2ca4-4423-4cab-b24e-86b99df38511)

- Manual preview for threshold Circle with CenterJDK enabled by default and manual brush radius

 [Manual preview for threshold Circle with CenterJDK enabled by default and manual brush radius.](https://github.com/cornerstonejs/cornerstone3D/assets/143810329/89a076b9-b2cc-440f-abba-23c75ae0fc93)

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

- [x] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS: macOS 14.5"
- [x] "Node version: v18.19.1"
- [x] "Browser: Chrome Version 125.0.6422.61 (Official Build) (arm64)"

### CODE REVIEW

**Comment by sedghi** [comment]
First and foremost, thank you for your contribution.

I'm trying to understand the purpose of the Center IJK Preview. What does it do when enabled or disabled?

I also noticed that the thresholdArea tool depends on which viewport it is hovered over (though there is a manual preview which picks the first viewport for some reason). I'm trying to understand if there is a specific use case you are targeting to pick the current slice only for thresholding. Why not threshold the entire volume?

I have seen numerous requests for a tool like this, but with the threshold applied to the whole segmentation, which I think makes more sense than the current view the tool is on.

https://community.ohif.org/t/how-to-apply-threshold-segmentation-automatically-in-ohif-3-8/1492/2
https://community.ohif.org/t/roi-threshold-tool-for-ct-images/911/2
https://community.ohif.org/t/what-steps-are-involved-in-enabling-the-roi-threshold-tool-for-ct-images-on-the-basic-viewer/921

What are your thoughts? I propose simplifying the ThresholdArea tool to obtain the segmentation volume and apply the threshold to the entire volume. Specifically, I suggest:

- Removing the center ijk preview
- Removing the manual preview

Are you open to these changes? Do you have the capacity to implement them?

**Comment by pavel-kaiko** [comment]
Hi @sedghi, 

First of all, thank you for checking and for responding. Let me address the questions and explain the purpose of the changes.

### Center IJK

> _I'm trying to understand the purpose of the Center IJK Preview. What does it do when enabled or disabled?_
Currently, if we want to visualise the Threshold within the brush area, it doesn't work. You need to place the center of the brush (Center IJK) directly above it. 
- **Example 1:**  The Center is above the area – the threshold is highlighted
   Screenshot 2024-06-14 at 13 15 50
- **Example 2:**  The Center is outside the area - the threshold is not highlighted (but exists inside of the brush radius)
  Screenshot 2024-06-14 at 13 15 37
- ** Example 3: ** Our proposal. Center IJK is disabled, and we can highlight the values within the brush radius without depending on the centre.  
  Screenshot 2024-06-14 at 13 21 23

> I also noticed that the thresholdArea tool depends on which viewport it is hovered over (though there is a manual preview which picks the first viewport for some reason). I'm trying to understand if there is a specific use case you are targeting to pick the current slice only for thresholding. Why not threshold the entire volume?

### Manual preview, Area, and others

**I'll start from the end.** 
1. I want to highlight the entire volume, but the process is slow, and the browser tab often crashes. Although I haven't had the time to check it, moving the calculations to web worker(s) could help with this issue. That's why I decided to implement the idea of highlighting Area – only one slice within the entire viewport.
2. A manual preview is needed to activate the highlighting without using the brush. Such a mode exists in Slicer – when you can turn highlighting `on` and `off`. In our viewer version, I trigger this method to activate the highlighting without the mouse needed. The downside of the current implementation is that it's not possible to draw when it's highlighted.
Screenshot 2024-06-14 at 13 41 27

3. I saw an interesting way of working when I activate the MPR mode and threshold—it uses the different (purple) segment to highlight, so I can draw, but when I deactivate the preview, it highlights, and everything disappears.
- During the process
  Screenshot 2024-06-14 at 13 42 40

- Preview (manual mode) switched off
  Screenshot 2024-06-14 at 13 42 49

### Summary
I am open to further improvements, but I already have limited capacity. We spent quite a lot of time implementing this feature and now need to focus more on other tasks for at least a few months. I am more likely to pick it up later or may be able to spend a few hours a week on it.

P.S. I will be on vacation, so I won't be able to respond to this thread for at least two weeks.

**Comment by sedghi** [comment]
Do you have the full volume threshold at some branch that I can try? I'm really interested in merging and maintaining that one. The slice based on the viewport is confusing in my opinion, and I'm not yet convinced that the centerIJK really adds value. However, I like the full volume approach, and I appreciate your work on it.

**Comment by sedghi** [comment]
As talked to @pavel-kaiko we will close this PR in favor of a new one based on the comments

**Pull request closed without merging**
