### PR TITLE
fix: package exports

### PR DESCRIPTION
**Pull request by Blackman99**
### Context

The current main field in package.json would cause app fail to import @cornerstone/xxx packages.
For example the current `main` field in @cornerstonejs/core package.json is `src/index.ts`, this would import the package as source code. But after bundled, it should not be imported as source code in other's projects. It would case error: `can not resolve src/index.ts in @cornerstonejs/core` .
It could happen in framework like NextJS or any project that doesn't recognize @cornerstonejs/xxx package as source code. 
As metioned in #882, but it is for beta 2 version
This PR is created for those using version 1

### Changes & Results

Add exports field in package.json in these packages to distinguish cjs and mjs usage

* @cornerstonejs/core
* @cornerstonejs/tools
* @cornerstonejs/nifti-volume-loader
* @cornerstonejs/streaming-image-volume-loader

### Testing

None

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

- [x] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS: Ubuntu 23.10
- [x] "Node version: 20.10.0 & 18.19.0
- [x] "Browser: Chrome 120.0.6099.201

### CODE REVIEW

**Review by sedghi — COMMENTED** [review]
For some reason this is failing the build
You can try it `cd packages/dicomImageLoader` then `yarn build` 

it gives this error 

CleanShot 2024-01-08 at 09 18 50

**Comment by sedghi** [comment]
Thanks for the update, one more thing. Can you please enhance the description of the PR on when it actually fails to import when you mentioned, which framework?

> The current main field in package.json would cause app fail to import @cornerstone/xxx packages

**Comment by Blackman99** [comment]
> Thanks for the update, one more thing. Can you please enhance the description of the PR on when it actually fails to import when you mentioned, which framework?
> 
> > The current main field in package.json would cause app fail to import @cornerstone/xxx packages

Added in the description of this PR.

**Comment by sedghi** [comment]
I know we merged in 2.x, since that was beta and less restrictions, but for 1.x which is considered stable I would like to get reproducible testing steps. What I'm looking for are steps (repo, any thing that I can clone, try) and shows the error and then try your fix and make sure it is fixed.  You mentioned NextJS, do you have a playground in NextJS that you can share that would fail on the main branch but works when we apply this PR fix?

**Comment by Blackman99** [comment]
> I know we merged in 2.x, since that was beta and less restrictions, but for 1.x which is considered stable I would like to get reproducible testing steps. What I'm looking for are steps (repo, any thing that I can clone, try) and shows the error and then try your fix and make sure it is fixed. You mentioned NextJS, do you have a playground in NextJS that you can share that would fail on the main branch but works when we apply this PR fix?

I can see your concern. Here's a reproduction link with stackbliz:
https://stackblitz.com/edit/stackblitz-starters-q3ogjh?file=app%2Fpage.tsx
Simply run this demo online will get this error:
image

**Comment by sedghi** [comment]
Thanks for the test.
I downloaded the project on stackBlitz to local, confirmed the bug, now I applied your patch/fix here, but still does not work. 

CleanShot 2024-01-11 at 08 20 03

Have you tried your fix in the stackBlitz you sent?

**Comment by Blackman99** [comment]
> Thanks for the test. I downloaded the project on stackBlitz to local, confirmed the bug, now I applied your patch/fix here, but still does not work.
> 
> CleanShot 2024-01-11 at 08 20 03
> 
> Have you tried your fix in the stackBlitz you sent?

If you want to fix this in the stackbliz. You can only apply the package.json changes to the local installed packages in node_modules

**Comment by sedghi** [comment]
@Blackman99 These were my steps

1. Downloaded your stackblitz to local
2. yarn/npm install (don't remember which)
3. Saw the original error you posted
4. Went into the local node_modules in the project (downloaded)
5. Applied the fixes
6. Saw new error I posted above

Am i missing something?

**Comment by Blackman99** [comment]
> @Blackman99 These were my steps
> 
> 1. Downloaded your stackblitz to local
> 2. yarn/npm install (don't remember which)
> 3. Saw the original error you posted
> 4. Went into the local node_modules in the project (downloaded)
> 5. Applied the fixes
> 6. Saw new error I posted above
> 
> Am i missing something?

After the changes applied. You may also need to clear the next cache by deleting the .next directory. The restart the project

**Comment by sedghi** [comment]
I tried deleting the .next and doesn't work still show me the new error. Are you certain it works for you after you apply that patch?

**Comment by Blackman99** [comment]
> I tried deleting the .next and doesn't work still show me the new error. Are you certain it works for you after you apply that patch?

Sorry, I forgot a change which is to remove `main` field in package.json

**Comment by sedghi** [comment]
Still no luck 

CleanShot 2024-01-11 at 22 18 23

I did remove .next first before yarn dev

**Comment by Blackman99** [comment]
That's strange. I'm using yarn by the way

**Comment by Blackman99** [comment]
I've noticed that in your screenshot. The package.json in the @cornerstonejs/streaming-image-volume-loader is not shown. Did you also apply the changes?

**Comment by sedghi** [comment]
Yeah applied there, didn't notice not including it in the screenshot

**Comment by sedghi** [comment]
CleanShot 2024-01-11 at 22 32 01

**Comment by Blackman99** [comment]
I don't quite know the reason. My changes basically are the same.
image
And my /page compiling is passed as shown in the terminal.

**Comment by sedghi** [comment]
I did a fresh download from stackblits and tried the steps, still the same new error. What is your node version? mine is 18.17.0

CleanShot 2024-01-12 at 08 22 24

**Comment by sedghi** [comment]
can you zip the whole folder with node_modules and everything and send it to me, just to see if that works, then we take a diff

**Comment by Blackman99** [comment]
> I did a fresh download from stackblits and tried the steps, still the same new error. What is your node version? mine is 18.17.0
> 
> CleanShot 2024-01-12 at 08 22 24

I've tried on node 20.10.0 and 18.19.0. And my OS is Ubuntu 23.10.

**Comment by baokeyu123** [comment]
i think, it's very necessarily for us to support MWA. for example react、angular、Vue .etc framework.
resolve and pull it, it seems beneficial to development. 
thank you~

**Comment by baokeyu123** [comment]
i think, it's very necessary for us to support MWA. for example react、angular、Vue .etc framework.
resolve and pull it, it seems beneficial to development.
thank you~

**Comment by sedghi** [comment]
@baokeyu123 Have you tried the stack blitz locally and tried the fix here and can confirm it resolves it?

**Comment by Blackman99** [comment]
I've tried on Windows10. It works as expected. How can I give the node_modules.zip file? @sedghi

**Comment by sedghi** [comment]
maybe dropbox or something? zip it

**Comment by Blackman99** [comment]
Try this:
https://www.dropbox.com/scl/fi/49pnfgguek83m7210j801/node_modules.zip?rlkey=nkvy8o6dmp2lym0otqt60b2hq&dl=0

**Comment by sedghi** [comment]
@IbrahimCSAE can you please check this for me? Please read through the conversation and reproducible steps and see if the fix works

**Comment by sedghi** [comment]
I did it in beta version, can you check it @Blackman99 ?

**Pull request closed without merging**
