### PR TITLE
feat(NiftiVolumeLoader): enable the nifti-volume-loader to read nifti file with datatype such as int32, float64, int8, uint16 and uint32. Because there is something wrong with function ‘createInt16SharedArray’ and ‘createUint16SharedArray’(window.crossOriginIsolated is false), Float32SharedArray is used for representing datatypes except for uint8.

### PR DESCRIPTION
**Pull request by SuperSuperKey**
### Context
[Feature Request] #964

### Changes & Results
Before: The nifti-volume-loader can not read nifti file with datatype such as int32, float64, int8, uint16 and uint32, so the cornerstone3D cannot render them.
After: The nifti-volume-loader can read nifti file with datatype such as int32, float64, int8, uint16 and uint32.

### Testing
Use the nifti-volume-loader component to load nifti file with datatype such as int32, float64, int8, uint16 and uint32.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

- [x] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS:  Ubuntu 18.04, macOS 14.2.1
- [x] "Node version:  v16.14.0
- [x] "Browser:
   Chrome 120.0.6099.234

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by sedghi** [comment]
Can you please share the data to test this?

**Comment by SuperSuperKey** [comment]
> Can you please share the data to test this?

Of course, I've uploaded the data to http://116.63.104.172/nifti_data.zip

**Comment by sedghi** [comment]
@SuperSuperKey Ok i"m much more free from now on
I can't download your data, can you please upload it somewhere else?

**Comment by SuperSuperKey** [comment]
> @SuperSuperKey Ok i"m much more free from now on I can't download your data, can you please upload it somewhere else?

Sure, I've uploaded the data to google drive (https://drive.google.com/file/d/1sLOBm3PGT2XOAWdPRdcyMLZ7tOB9fCcT/view?usp=drive_link).

**Comment by sedghi** [comment]
Thank you for your PR. I believe this new PR offers better support, so I will close your PR in favor of it.

https://github.com/cornerstonejs/cornerstone3D/pull/1219

**Pull request closed without merging**
