### PR TITLE
docs(Example): Update Segmentation Volume

### PR DESCRIPTION
**Pull request by jlopes90**
### Testing

Example Segmentation Volume
https://deploy-preview-1201--cornerstone-3d-docs.netlify.app/live-examples/segmentationVolume.html

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by jlopes90** [comment]
Don't merge yet, only when I say

**Comment by jlopes90** [comment]
@sedghi 

## Before

When loading dicom and segmentation, the segmentation is opposite or incorrect.
```javascript
async function fetchDicom() {
    imageIds = await createImageIdsAndCacheMetaData(exConfig.fetchDicom);
    await loadDicom(imageIds);
}
```

image

## After

I changed the `loadDicom(imageIds)` to `loadDicom(imageIds.reverse())`, this is dicom loading.
When loading dicom and segmentation, the segmentation is correct.
```javascript
async function fetchDicom() {
    imageIds = await createImageIdsAndCacheMetaData(exConfig.fetchDicom);
    await loadDicom(imageIds.reverse());
}
```

image

But why?

**Comment by l5769389** [comment]
bug like the link https://github.com/cornerstonejs/cornerstone3D/issues/1170#issuecomment-2046749766

**Comment by l5769389** [comment]
@jlopes90， i find reverse the imageIds can match as you said。 bug will cause the segmentation and volume mismatch in volume render。as the figure after i reverse the imageIds。 left mpr 3 viewers works，but right error。 
图片

**Pull request merged**
