### PR TITLE
fix(nifti): the volume ID check in case of scrolling for nifti volume

### PR DESCRIPTION
**Pull request by SachidanandAlle**
This should solve: https://github.com/cornerstonejs/cornerstone3D/issues/1138

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by SachidanandAlle** [comment]
@sedghi can you help to fix this.  
We are planning to use Cornerstone JS to render nifti volume+masks

**Comment by SachidanandAlle** [comment]
@wayfarer3130 @sedghi @pieper please help here.. 
this is kind of urgent requirement for NVIDIA to use cornerstone JS to render nifti files in it's playground.  but currently not able to scroll due this bug.

Atleast verified for couple of samples to be working good with this fix.

**Comment by SachidanandAlle** [comment]
feel free to have any other best solution or PR to fix this issue. 

but please unblock the scroll issue over loaded nifti images asap

**Comment by SachidanandAlle** [comment]
Anyone else who can help quick? @dannyrb @JamesAPetts @swederik ?

**Comment by sedghi** [comment]
let me look at this right now, I didn't notice it is you @SachidanandAlle

**Comment by SachidanandAlle** [comment]
> let me look at this right now, I didn't notice it is you @SachidanandAlle

can we get it merged.. need npm package for GTC launch.. to show-case one of the medical use case

**Comment by SachidanandAlle** [comment]
This was noticed when we load nifti volume

targetVolumeID: nifti:http://10.117.6.209:36868/example-1.nii.gz?sliceIndex=105&viewPlaneNormal=0,0,-1&focalPoint=-196,-196,105

vs

volumeId: nifti:http://10.117.6.209:36868/example-1.nii.gz

**Comment by sedghi** [comment]
I pushed some more fixes, window level was broken too
CI pass -> merge

**Review by sedghi — APPROVED** [review]

**Comment by SachidanandAlle** [comment]
@sedghi 
I pulled the latest changes and verified it to be working.  Thanks for the quick help :)

**Comment by SachidanandAlle** [comment]
https://app.circleci.com/pipelines/github/cornerstonejs/cornerstone3D

@sedghi Something wrong? or the npm build/publish workflow is running?

image

**Comment by sedghi** [comment]
it's fine as I see

https://www.npmjs.com/package/@cornerstonejs/core

**Comment by SachidanandAlle** [comment]
> it's fine as I see
> 
> https://www.npmjs.com/package/@cornerstonejs/core

Thank you.. it got pushed after few hours later.. and we could use the package and verify all e2e..

**Pull request merged**
