### PR TITLE
fix: Capture error messages thrown by vtk

### PR DESCRIPTION
**Pull request by baokeyu123**
### Context
Due to vtk.js  version update.
DataArray.js add  conditional judgment 
```javascript
  if (model.size % model.numberOfComponents !== 0) {
    throw new RangeError('model.size is not a multiple of model.numberOfComponents');
  }
```
i think that we should add condition to capture error message in Vtk.

image

### Changes & Results

Capture error information by dispatch  `Events.IMAGE_LOAD_ERROR`

### Testing

after:
image

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

- [x] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS: 
- [x] "Node version: 
- [x] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by sedghi** [comment]
I think this is related PR https://github.com/cornerstonejs/cornerstone3D/pull/1043
Do you actually have any data to test this? Unfortunately, I don't have any data to test for 1043.

**Comment by baokeyu123** [comment]
> Do you actually have any data to test this? Unfortunately, I don't have any data to test for 1043

yes. dicom tag(00280004) is RGB.
But `PR1043` is only for the changes made to RGB DICOM. I have not tested all color(such as RGBA,MONOCHROME2,MONOCHROME1,YBR_FULL).
createVTKImageData error information can be captured through PR code.

**Comment by Blackman99** [comment]
This is exactly what we're facing too.

**Comment by sedghi** [comment]
If someone can provide test data, I would be happy to test and merge this. Unfortunately, I cannot blindly approve it without the necessary information.

**Comment by Blackman99** [comment]
The current `Promise.allSettled` function would always return a array, the item of which is either a fullfilled or a rejected promise. The problem is the current code do nothing even if there are some **rejected results**. It would cause the user get nothing when some error happened.

This PR add the error handle part which can handle any error happed during `getLoaderImageOptions` and dispatch the `IMAGE_LOAD_ERROR` event by `eventTarget`.  So the user can use the `eventTarget.addEventListener` to get error message

**Comment by baokeyu123** [comment]
> If someone can provide test data, I would be happy to test and merge this. Unfortunately, I cannot blindly approve it without the necessary information.

Firstly,based on `dicomImageLoader`'s wadors to load Dicom image（cornerstoneDICOMImageLoader.wadors.metaDataManager.add(imageId，metadata)).
Secondly,accept set  `multipart/related;type=application/dicom`   in request header.
Finally,make sure dicom tag (0028004) is RGB.
Regardless of `PR1038` and `PR1043`, the problem can be reproduced.
I don't think it can be reproduced simply by giving you the .dcm file.I have to think about how to help you reproduce the problem.

**Review by sedghi — APPROVED** [review]
Makes sense thanks

**Pull request merged**
