### PR TITLE
[WIP]: Example/rtss

### PR DESCRIPTION
**Pull request by dxlin**
WIP - segmentToRTSS example has function for converting segmentation volume to ROIContour to be sent to dcmjs for export. Conversion to contour is performed via vtkImageMarchingSquares routine on each of the slices.

1. Currently missing Referenced Image UIDs, should this be populated instead in dcmjs?
2. Would the conversion function be best placed in a tool or as a general util?

### CODE REVIEW

**Comment by sedghi** [comment]
Hey, glad to see that you have some progress on this. One small note, you need to add the name of the example folder [here](https://github.com/cornerstonejs/cornerstone3D-beta/blob/ed23f05b23063769942328f9e6797d792767ec49/utils/ExampleRunner/example-info.json) for it to show up in the demo page.

Looking forward to try it

**Comment by dxlin** [comment]
Thanks for notice! I've updated with the changes.

The example at the moment only outputs the contour object in the console. The intention is for this object to be passed to dcmjs for export.

**Comment by sedghi** [comment]
@dxlin Cornerstone3D does not have dependency on dcmjs (and we don't want to add that), hmmm, I'm wondering if then PR to Cornerstone is a bad idea. Let's try to implement the non-dcmjs part of the functionalities in the tools, and then the demo itself can have dependency on the dcmjs (right now some of them does).

**Comment by sedghi** [comment]
Done in another PR https://github.com/cornerstonejs/cornerstone3D/pull/734

**Pull request closed without merging**
